### ISSUE TITLE
文件代码 询问

### ISSUE THREAD

**Issue by dora-admin001** [eooce/nodejs-reality#1]
我想请问大佬，
在index.js里第四行 “const subtxt = './app/url.txt' ”
这个app的文件夹是不是错的啊？
在start.sh里显示是 .npm
经过容器测试，文件名改成.npm，/sub就能显示base64了

**Comment by eooce** [comment]
路径自己改就是了，不支持多端口的玩具不要开http，否则节点不通，支持多端口的可以填正确的路径，两边对应可以启用订阅功能
